### ISSUE TITLE
Release failed: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by Locietta** [Locietta/xanmod-kernel-WSL2#10]
release somehow failed with
```
Error: Cannot read property 'data' of undefined
```

The issue is already at softprops/action-gh-release#221.
Seems like just a re-run could fix this failure🤔

**Comment by Locietta** [comment]
> Seems like just a re-run could fix this failure🤔

Partial rerun of release job in the workflow doesn't work though, maybe a thorough rerun can help?
Anyway, it looks like a internal TypeScript Error in the release action...

**Comment by Locietta** [comment]
> Partial rerun of release job in the workflow doesn't work though, maybe a thorough rerun can help? 
No luck...

**Comment by Locietta** [comment]
So it's probably not my mistake in `build.yml`, since revert back to the last successful release doesn't change the situation. Still don't know what happens.

**Comment by Locietta** [comment]
Going to see if changing the version of release action works.

**Comment by Locietta** [comment]
can't reproduce with minimal `.yml` file at [here](https://github.com/Locietta/github-action-playground/commit/c0f45cd6aaa6fc73faacb57787a85824ef4d2d32)

**Comment by Locietta** [comment]
Get a [minimal reproduce](https://github.com/Locietta/github-action-playground/actions/runs/2149362162).

**Comment by Locietta** [comment]
But we still keep failing even with the correct `release.yml`

**Comment by Locietta** [comment]
So `Cannot read property 'data' of undefined` is caused by my broken `release.yml`, and the reason why fix in PR didn't work is the release default tag to `main` branch, where the `release.yml` is still broken. 

Solution is easy: set `target_commitish` to commit sha of current branch. 

But be careful as `${{ github.sha }}` will return sha of the merge commit, not the latest commit we push. That's a bit tricky, so you may want something like:

```yaml
    - id: fetch_commit_sha
      run: |
        if [ ${{ github.event_name == 'pull_request' }} ]; then
          echo "::set-output name=sha::${{ github.event.pull_request.head.sha }}"
        else 
          echo "::set-output name=sha::${{ github.sha }}"
        fi
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        target_commitish: ${{ steps.fetch_commit_sha.outputs.sha }} 
        ......
```
